services:
  - type: web
    name: gayaseva-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: KEEP_ALIVE_INTERVAL_MINUTES
        value: 5
      - key: RENDER_EXTERNAL_URL
        value: https://gayaseva-backend.onrender.com
      - key: DATABASE_URL
        value: postgresql://postgres:KthIu1hwY2Lg5DkL@db.skhvpstqruswldkzksdz.supabase.co:5432/postgres
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://skhvpstqruswldkzksdz.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_oiliOrp73qv098OT2J--Gw__OV1pnS7
      - key: CORS_ORIGIN
        value: https://gayaseva.com
